[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "spending-monitor-evaluation"
dynamic = ["version"]
description = "Rule evaluation scaffolding"
requires-python = ">=3.11"
license = "MIT"

[project.optional-dependencies]
dev = [
  "pytest>=7.4.0",
]

[tool.hatch.version]
path = "src/evaluation/__init__.py"


