version: '3'

services:
  zookeeper:
    image: quay.io/strimzi/kafka:0.41.0-kafka-3.7.0
    container_name: zookeeper
    command: ["sh", "-c", "bin/zookeeper-server-start.sh config/zookeeper.properties"]
    networks:
      - kafka-network
    environment:
      LOG_DIR: /tmp/logs
    ports:
      - "2181:2181"
    healthcheck:
      test: ["CMD-SHELL", "echo 'ls /' | bin/zookeeper-shell.sh localhost:2181 | grep zookeeper"]
      interval: 15s
      timeout: 10s
      retries: 5
  
  kafka:
    image: quay.io/strimzi/kafka:0.41.0-kafka-3.7.0
    container_name: kafka
    networks:
      - kafka-network
    environment:
      LOG_DIR: /tmp/logs
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    command: ["sh", "-c", "bin/kafka-server-start.sh config/server.properties --override listeners=PLAINTEXT://:9092 --override advertised.listeners=PLAINTEXT://localhost:9092 --override zookeeper.connect=zookeeper:2181"]
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    healthcheck:
      test: ["CMD", "bin/kafka-topics.sh", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 15s
      timeout: 10s
      retries: 5
    
networks:
  kafka-network:
    external: false